name: "build-latest"

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "src/Dockerfile*"

jobs:
  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Setting up Bash Automated Testing System
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.5.0

      - name: Checkout the repository
        uses: actions/checkout@v3.0.1

      - name: Running Bash tests
        run: bats --tap --recursive --timing tests/

  docker_buildx_debian:
    needs: run_tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.1

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          build-args: BUILDX_QEMU_ENV=true
          tags: thexaf/nginx-certbot:latest

  docker_buildx_alpine:
    needs: run_tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.1

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest Alpine image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./src
          file: ./src/Dockerfile-alpine
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: thexaf/nginx-certbot:latest-alpine
