name: "build-tags"

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v[1-9].[0-9]+.[0-9]+-nginx[1-9].[0-9]+.[0-9]+"

jobs:
  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Setting up Bash Automated Testing System
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.5.0

      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Running Bash tests
        run: bats --tap --recursive --timing tests/

  docker_buildx_debian:
    needs: run_tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Extract version numbers from GitHub reference
        id: tagger
        run: bash .github/version_extractor.sh ${GITHUB_REF}

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push all Debian images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          pull: true
          no-cache: true
          push: true
          build-args: BUILDX_QEMU_ENV=true
          tags: |
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}.${{ steps.tagger.outputs.APP_PATCH }}
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}.${{ steps.tagger.outputs.APP_PATCH }}-nginx${{ steps.tagger.outputs.NGINX_VERSION }}

  docker_buildx_alpine:
    needs: run_tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Extract version numbers from GitHub reference
        id: tagger
        run: bash .github/version_extractor.sh ${GITHUB_REF}

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push all Alpine images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile-alpine
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          pull: true
          no-cache: true
          push: true
          tags: |
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}-alpine
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}-alpine
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}.${{ steps.tagger.outputs.APP_PATCH }}-alpine
            thexaf/nginx-certbot:${{ steps.tagger.outputs.APP_MAJOR }}.${{ steps.tagger.outputs.APP_MINOR }}.${{ steps.tagger.outputs.APP_PATCH }}-nginx${{ steps.tagger.outputs.NGINX_VERSION }}-alpine

  update_docker_hub_docs:
    needs:
      - docker_buildx_debian
      - docker_buildx_alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: Create Docker Hub documentation
        run: cat docs/dockerhub_tags.md > tmp.md && cat README.md >> tmp.md

      - name: Upload Docker Hub description
        uses: peter-evans/dockerhub-description@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: thexaf/nginx-certbot
          readme-filepath: ./tmp.md
