name: "Running automated tests"

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!master'
  pull_request:

jobs:
  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Setting up Bash Automated Testing System
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.5.0

      - name: Checkout the repository
        uses: actions/checkout@v4.0.0

      - name: Running Bash tests
        run: bats --tap --recursive --timing tests/
